### ISSUE TITLE
Can't import itself - ans1.js

### ISSUE THREAD

**Issue by aldensc** [crypto-browserify/parse-asn1#23]
File ans1.js has the following line of code...

var asn1 = require('asn1.js')

If you use any syntax checking (rollup/lint/babel), it will flag this as an error.
> rollup --environment NODE_ENV:development,NODE_VEND
ollup.config.js

bundling...
?   A module cannot import itself
node_modules\parse-asn1\asn1.js (1:0)
1: import 'asn1.js';
   ^
2: import './certificate';
3: import require$$0 from ' commonjs-proxy:asn1.js';

**Comment by calvinmetcalf** [comment]
If it doesn't start with a './' it's referring to a module on npm not a
file, this is a bug in the rollup commonjs implementation
