### ISSUE TITLE
Package won't install because `asn1.js@4.10.0` no longer exists

### ISSUE THREAD

**Issue by joelalejandro** [crypto-browserify/parse-asn1#24]
If you try to download [asn1.js@4.10.0](https://registry.npmjs.org/asn1.js/-/asn1.js-4.10.0.tgz), the NPM registry can't find it:

```json
{
  "error": "package could not be found."
}
```

**Comment by calvinmetcalf** [comment]
this is almost certainly a local cache issue on your part
