### ISSUE TITLE
fixProc startRegex "PUBLIC KEY"

### ISSUE THREAD

**Issue by CarstenHouweling** [crypto-browserify/parse-asn1#35]
fixProc.js line 25 `var tag = key.match(startRegex)[1]` does not return "PUBLIC KEY" because the startRegex fails. 

See https://regex101.com/ for example. Enter the startRegex: `/^-----BEGIN ((?:.* KEY)|CERTIFICATE)-----/m`, then enter a random public key `-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7pzpogb1ZPndhnElpSuflFMmYbdRh4WrBZ6cE14Qrn1nfuLCDm86b8YGZiExCsWYbUSO8SuF3JXYTf67xfSRGLo52h3pvKORcLbBD6MkC4BgNYxncco6TvFVLBea4lPTNWiOmVmmB72DUliBjdApeP/CHSjNSxLXHnh2hUDeeZFBozMgKw0R8MuunGNzUuyg7UCgF1sebt8j/szvHzvevshP9o299jXavVcxZ2q6f9zO04vX7gp4ZxMezyAeDEC+m7Lg32XzYm81zEzFxX6nFZUOC0q+DbqcNsRkkzfmsYgRF2FAat4M/OeRBAJKqg3mQMIiY5+xTdEUWP8NeOwZJQIDAQAB-----END PUBLIC KEY-----`.

The regex returns `PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7pzpogb1ZPndhnElpSuflFMmYbdRh4WrBZ6cE14Qrn1nfuLCDm86b8YGZiExCsWYbUSO8SuF3JXYTf67xfSRGLo52h3pvKORcLbBD6MkC4BgNYxncco6TvFVLBea4lPTNWiOmVmmB72DUliBjdApeP/CHSjNSxLXHnh2hUDeeZFBozMgKw0R8MuunGNzUuyg7UCgF1sebt8j/szvHzvevshP9o299jXavVcxZ2q6f9zO04vX7gp4ZxMezyAeDEC+m7Lg32XzYm81zEzFxX6nFZUOC0q+DbqcNsRkkzfmsYgRF2FAat4M/OeRBAJKqg3mQMIiY5+xTdEUWP8NeOwZJQIDAQAB-----END PUBLIC KEY` which in turn fails parse-asn1 index.js `switch (type)`.

When i force the type to be `PUBLIC KEY` All is well.

**Comment by calvinmetcalf** [comment]
that's becasue you are missing a line break at the end of the first line

**Comment by calvinmetcalf** [comment]
that being said that shouldn't matter and I think it's an easy fix
