### ISSUE TITLE
Upgrade asn1.js to ^5.2.0

### ISSUE THREAD

**Issue by voluntadpear** [crypto-browserify/parse-asn1#39]
The usage of `eval` was removed from `asn1.js` a few days ago (https://github.com/indutny/asn1.js/issues/108) but `parse-asn1` still depends on `asn1.js@4`. Could it be bumped to the latest version?

**Comment by shrpne** [comment]
Updated in https://github.com/crypto-browserify/parse-asn1/releases/tag/v5.1.6

**Comment by calvinmetcalf** [comment]
this is fixed

**Comment by cnemo-cenic** [comment]
the fix was reverted https://github.com/browserify/parse-asn1/commit/f23087045497c93bd0a151e29b1e3f738e898cb8

I currently have the following override:

```
"parse-asn1": {
  "asn1.js": "^5.4.1"
}
```

perhaps node <4 users should be the ones invoking the override? I don't know what % of your user base that is.

**Comment by ljharb** [comment]
@cnemo-cenic that's how how semver works; if a bugfix is breaking, the bug has to be fixed another way.

**Comment by cnemo-cenic** [comment]
Can't you do `^5.0.0 || ^4.10.1`?

**Comment by ljharb** [comment]
no, because then npm will install v5, which is a breaking change. pnpm is the only one that installs the lowest matching by default.

**Comment by cnemo-cenic** [comment]
from my POV your change, four years after the fix was made, was the breaking one

**Comment by ljharb** [comment]
Not from semver's, though, which is what matters.
