### ISSUE TITLE
asn.define is not a function

### ISSUE THREAD

**Issue by Sleep1ngosu** [crypto-browserify/parse-asn1#48]
Cannot use browserify-sign because of this problem

![Image](https://github.com/user-attachments/assets/ede3ab86-8875-44da-b482-a42b853f1613)

**Comment by ljharb** [comment]
What version of `asn1.js` are you using? line 7 of https://unpkg.com/browse/asn1.js@5.4.1/lib/asn1.js clearly indicates that it is a function.

**Comment by Sleep1ngosu** [comment]
4.10.1
It's installed as dependency from parse-asn1 package.json

**Comment by ljharb** [comment]
line 5 of https://unpkg.com/browse/asn1.js@4.10.1/lib/asn1.js has it too.
